# This code gathers publication data from Scopus and Web of Science's API.

Both sources give us access to their APIs for easily gathering publication data. The code below turns the information gathered from the API into Excel files or input directly into a SQLite3 database.

In [1]:
import pandas as pd
import matplotlib as plt
import pyalex
from pyalex import Works, Authors, Sources, Institutions, Topics, Publishers, Funders
import requests as req
import re
import json
import pybliometrics
from pybliometrics.scopus import ScopusSearch
from pybliometrics.scopus import SerialTitleSearch
import sqlite3
import clarivate.wos_starter.client
import os
import time
from clarivate.wos_starter.client.rest import ApiException
from pprint import pprint
import xlsxwriter
import requests as req
import re
import json
import warnings
import getpass

warnings.filterwarnings("ignore") #This is here to improve performance time. However, if you are repairing, improving, or otherwise testing this code, it is recommended to comment this out.

# Connect to Publication Database

### If you are planning on turning the publication data into an Excel file instead, you can skip this cell.

In [3]:
conn = sqlite3.connect(r"C:\Users\aharrima\OneDrive - University of Tennessee\Documents\UTK_Publications.db")
cur = conn.cursor()

# Scopus

#### More details on the Scopus package and its functionality can be found here: https://github.com/alistairwalsh/scopus

### The Scopus package uses Scopus' advanced search feature to gather publications, meaning that we need to provide it some search functions instead of keywords. Some of the most important functions for Scopus gathering include:

AF-ID () - The affiliation ID, best method for gathering publications from an institution. The best way to get this info is to go to Scopus directly and search for the institution, which will store the ID in the search history. See below for commonly used AF-IDs.

PUBYEAR - Used for publication year. Treated like a number, so PUBYEAR > X and PUBYEAR = Y are allowed. No parentheses needed.

AUTHLASTNAME() and AUTHFIRSTNAME() - Used for author names. When gathering articles, this will only return the first 100 authors of an article.

REF() - Used for references, such as finding the articles that cite another article.

### Important Affiliation IDs for Scopus Gathering:

The information that goes into AF-ID (  ) when searching for a specific institution. Leave a space before and after the ID itself. For example: AF-ID ( "university" 86753091 )

UT Knoxville - "the university of tennessee, knoxville" 60015574

Montana State - "Montana State University" 60022522

In [33]:
# Initialize the Scopus API Functions

pybliometrics.scopus.init()

### Before running the search, check to see the size of what you are downloading. Large downloads will take several minutes to gather from Scopus.

In [32]:
searchSizeCheck = ScopusSearch('PUBYEAR > 2013 AND PUBYEAR < 2026 AND AF-ID ( "the university of tennessee, knoxville" 60015574 )', download = False)

searchSizeCheck.get_results_size()

46799

### Download Scopus Data

The Scopus package comes with an automatically generated progress bar that includes how long it expects it'll take to gather all of your articles.

In [34]:
scopusPubsSearchUTK = ScopusSearch('PUBYEAR > 2013 AND PUBYEAR < 2026 AND AF-ID ( "the university of tennessee, knoxville" 60015574 )', verbose = True)

Downloading results for query "PUBYEAR > 2013 AND PUBYEAR < 2026 AND AF-ID ( "the university of tennessee, knoxville" 60015574 )":

100%|██████████| 1872/1872 [38:03<00:00,  1.22s/it]

AttributeError: 'ScopusSearch' object has no attribute 'shape'

### Convert to a DataFrame

In [35]:
scopusPubsUTK = pd.DataFrame(scopusPubsSearchUTK.results)

scopusPubsUTK.columns

Index(['eid', 'doi', 'pii', 'pubmed_id', 'title', 'subtype',
       'subtypeDescription', 'creator', 'afid', 'affilname',
       'affiliation_city', 'affiliation_country', 'author_count',
       'author_names', 'author_ids', 'author_afids', 'coverDate',
       'coverDisplayDate', 'publicationName', 'issn', 'source_id', 'eIssn',
       'aggregationType', 'volume', 'issueIdentifier', 'article_number',
       'pageRange', 'description', 'authkeywords', 'citedby_count',
       'openaccess', 'freetoread', 'freetoreadLabel', 'fund_acr', 'fund_no',
       'fund_sponsor'],
      dtype='object')

In [36]:
scopusPubsUTK.shape

(46799, 36)

## Get the Publication Campus and Year

In [142]:
scopusPubsUTK['Publication Campus'] = 'UT Knoxville'

scopusPubsUTK['Year'] = scopusPubsUTK['coverDate'].str.slice(0, 4)

scopusPubsUTK = scopusPubsUTK.astype({'Year': int})

### Save to Database

Only use if you have already connected to a database in the cell above.

In [143]:
scopusPubsUTK.to_sql('scopus_pubs_utk_update2025', conn, if_exists = 'replace', index = False)

46799

### Save to Excel

Only use if you are not connecting to a database, or if you want a backup to the database.

In [ ]:
scopusPubsUTK.to_excel('Scopus API Download Test.xlsx')

# Web of Science

#### More details on the Web of Science API package and its functionality can be found here: https://github.com/clarivate/wosstarter_python_client?tab=readme-ov-file

As of March 18, 2026, we have access to the Standard Subscriber API, not the Extended API nor the Institutional level.

## Initialize the API and Run the Query

### Similar to Scopus, Web of Science's API uses its advanced search features to gather publications. A table containing all variables you can query on and the format to do so can be found at the above GitHub link.

In [2]:
# Defining the host is optional and defaults to http://api.clarivate.com/apis/wos-starter/v1
# See configuration.py for a list of all supported configuration parameters.
configuration = clarivate.wos_starter.client.Configuration(
    host = "https://api.clarivate.com/apis/wos-starter/v1"
)

# Load the API Key

os.environ["API_KEY"] = getpass.getpass('Enter your Web of Science API Key:')

## Each project should have its own API Key, which can be created from the Web of Science API admin page.


# Configure API key authorization: ClarivateApiKeyAuth
configuration.api_key['ClarivateApiKeyAuth'] = os.environ["API_KEY"]



# Enter a context with an instance of the API client
with clarivate.wos_starter.client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = clarivate.wos_starter.client.DocumentsApi(api_client)
    query = '(OG=(University of Tennessee Knoxville)) AND PY=(2025)'
    database = 'WOS' # Web of Science Database abbreviation * WOS - Web of Science Core collection * BIOABS - Biological Abstracts * BCI - BIOSIS Citation Index * BIOSIS - BIOSIS Previews * CCC - Current Contents Connect * DIIDW - Derwent Innovations Index * DRCI - Data Citation Index * MEDLINE - MEDLINE The U.S. National Library of Medicine® (NLM®) premier life sciences database. * ZOOREC - Zoological Records * PPRN - Preprint Citation Index * WOK - All databases  (optional) (default to 'WOS')
    recordLimit = 50 # set the limit of records on the page (1-50) (optional) (default to 10)
    resultPage = 1 # set the result page (optional) (default to 1)
    sort_field = 'TC+D' # Order by field(s). Field name and order by clause separated by '+', use A for ASC and D for DESC, ex: PY+D. Multiple values are separated by comma. Supported fields:  * **LD** - Load Date * **PY** - Publication Year * **RS** - Relevance * **TC** - Times Cited  (optional)
    modified_time_span = None # Defines a date range in which the results were most recently modified. Beginning and end dates must be specified in the yyyy-mm-dd format separated by '+' or ' ', e.g. 2023-01-01+2023-12-31. This parameter is not compatible with the all databases search, i.e. db=WOK is not compatible with this parameter. (optional)
    tc_modified_time_span = None # Defines a date range in which times cited counts were modified. Beginning and end dates must be specified in the yyyy-mm-dd format separated by '+' or ' ', e.g. 2023-01-01+2023-12-31. This parameter is not compatible with the all databases search, i.e. db=WOK is not compatible with this parameter. (optional)
    detail = None # it will returns the full data by default, if detail=short it returns the limited data (optional)

    try:
        # Query Web of Science documents 
        api_response = api_instance.documents_get(query, 
                                                  db=database, 
                                                  limit=recordLimit,
                                                  page=resultPage, 
                                                  sort_field=sort_field, 
                                                  modified_time_span=modified_time_span, 
                                                  tc_modified_time_span=tc_modified_time_span, 
                                                  detail=detail)
        #print("The response of DocumentsApi->documents_get:\n")
        #pprint(api_response)
    except ApiException as e:
        print("Exception when calling DocumentsApi->documents_get: %s\n" % e)

Enter your Web of Science API Key: ········

### Check the Query Size

Web of Science will only show up to 50 items by default, as this is the size of one page. However, the full length of the query is shown within the metadata.

If the query is larger than 50 publications, the bulk load section can be used to gather many pages at once.

In [3]:
dictTest = api_response.to_dict()

dictTest['metadata']

{'page': 1, 'limit': 50, 'total': 4652}

# Turn Single Page into Publication Data Table

If each portion of the code shown below is working and you need to gather more than one page's worth of articles (more than 50), scroll down to the bulk load section below.

### uID, Title, Source Type

In [11]:
titleSource = pd.DataFrame.from_dict(dictTest['hits'])[['uid', 'title', 'types', 'sourceTypes']]

titleSource

,uid,title,types,sourceTypes
0,WOS:000272455700005,The Role of Propagule Pressure in Biological I...,"[Review, Book]","[Review, Book Chapter]"
1,WOS:000262615800025,Adolescent Romantic Relationships,"[Review, Book]","[Review, Book Chapter]"
2,WOS:000348451900012,Designing Radiation Resistance in Materials fo...,"[Review, Book]","[Review, Book Chapter]"
3,WOS:000280818700011,The Indentation Size Effect: A Critical Examin...,"[Review, Book]","[Review, Book Chapter]"
4,WOS:000252359800019,Sympatric speciation: Models and empirical evi...,"[Review, Book]","[Review, Book Chapter]"
5,WOS:000329821800013,Community and Ecosystem Responses to Elevation...,"[Review, Book]","[Review, Book Chapter]"
6,WOS:000306933700013,Health Benefits of n-3 Polyunsaturated Fatty A...,"[Article, Book]","[Article, Book Chapter]"
7,WOS:000412189800010,Viruses in Soil Ecosystems: An Unknown Quantit...,"[Article, Book]","[Article, Book Chapter]"
8,WOS:000323371300002,The Appalachian orogen: A brief summary,"[Editorial material, Book]","[Editorial Material, Book Chapter]"
9,WOS:000341798800002,Diversity of <i>Bacillus thuringiensis</i> Cry...,"[Review, Book]","[Review, Book Chapter]"
10,WOS:000614643200008,Mechanisms of Resistance to Insecticidal Prote...,"[Review, Book]","[Review, Book Chapter]"
11,WOS:000474601200013,Materials for Automotive Lightweighting,"[Review, Book]","[Review, Book Chapter]"
12,WOS:000311573500013,Evolutionary Inferences from Phylogenies: A Re...,"[Review, Book]","[Review, Book Chapter]"
13,WOS:000348560700017,Microbial Responses to the <i>Deepwater Horizo...,"[Review, Book]","[Review, Book Chapter]"
14,WOS:000329821800016,Introgression of Crop Alleles into Wild or Wee...,"[Review, Book]","[Review, Book Chapter]"
15,WOS:000240319400005,Innovative dietary sources of n-3 fatty acids,"[Review, Book]","[Review, Book Chapter]"
16,WOS:000275616000006,Microbial Fingerprinting using Matrix-Assisted...,"[Review, Book]","[Review, Book Chapter]"
17,WOS:000363420400007,Fuzzy Judgments and Fuzzy Sets,"[Article, Book]","[Article, Book Chapter]"
18,WOS:000321737800009,Naturally Occurring Antimicrobials for Minimal...,"[Review, Book]","[Review, Book Chapter]"
19,WOS:000301369500011,Developing global leadership capabilities and ...,"[Article, Book]","[Article, Book Chapter]"
20,WOS:000307953100010,Plasmodesmata Paradigm Shift: Regulation from ...,"[Review, Book]","[Review, Book Chapter]"
21,WOS:000362823900001,The Planetary Condition Introduction,"[Editorial material, Book]","[Editorial Material, Book Chapter]"
22,WOS:000279003400034,Chemical Preservatives and Natural Antimicrobi...,"[Article, Book]","[Article, Book Chapter]"
23,WOS:000296559500002,Patterns of Parenting Across Adolescence,"[Article, Book]","[Article, Book Chapter]"
24,WOS:000280437400005,"EVALUATIVE CONDITIONING: THE ""HOW"" QUESTION","[Article, Book]","[Article, Book Chapter]"
25,WOS:000495572600014,Climate Change in the Tropics: Ecological and ...,"[Review, Book]","[Review, Book Chapter]"
26,WOS:000322045500002,Carbon Mineralogy and Crystal Chemistry,"[Review, Book]","[Review, Book Chapter]"
27,WOS:000613949100024,Climate Disruption of Plant-Microbe Interactions,"[Review, Book]","[Review, Book Chapter]"
28,WOS:000319779700005,A Three-Tier Hierarchy of Self-Potency: Indivi...,"[Article, Book]","[Article, Book Chapter]"
29,WOS:000321197500010,Bacterial Entomopathogens,"[Article, Book]","[Article, Book Chapter]"
30,WOS:000334339600015,Radiation Damage Theory,"[Article, Book]","[Article, Book Chapter]"
31,WOS:000405166900006,On the Panculturality of Self-enhancement and ...,"[Article, Book]","[Article, Book Chapter]"
32,WOS:000268201500001,Introduction to Full Factorial Designs with Tw...,"[Editorial material, Book]","[Editorial Material, Book Chapter]"
33,WOS:000371430700011,"Organic Nanoparticles in Foods: Fabrication, C...","[Review, Book]","[Review, Book Chapter]"
34,WOS:000311379300018,Multilevel Power Converters,"[Article, Book]","[Article, Book Chapter]"
35,WOS:000240466600007,Projecting yield and utilization potential of ...,"[Review, Book]","[Review, Book Chapter]"
36,WOS:000336929500025,Development and Application of a Deterministic...,"[Article, Book]","[Article, Book Chapter]"
37,WOS:000286334500002,An introduction to ground penetrating radar (GPR),"[Editorial material, Book]","[Editorial Material, Book Chapter]"
38,WOS:000389751400020,Molecular Soybean-Pathogen Interactions,"[Review, Book]","[Review, Book Chapter]"
39,WOS:000263265300003,Diversity in Bacterial Chemotactic Responses a...,"[Review, Book]","[Review, Book Chapter]"
40,WOS:000433067800012,Kinesins and Myosins: Molecular Motors that Co...,"[Review, Book]","[Review, Book Chapter]"
41,WOS:000388837200064,Multiple Mobile Robot Systems,"[Article, Book]","[Article, Book Chapter]"
42,WOS:000368846600014,Anaerobic Soil Disinfestation and Soilborne Pe...,"[Article, Book]","[Article, Book Chapter]"
43,WOS:000361326200002,Is Sexual Behavior Healthy for Adolescents? A ...,"[Article, Book]","[Article, Book Chapter]"
44,WOS:000340899900005,Inclusion of costs in conservation planning de...,"[Article, Book]","[Article, Book Chapter]"
45,WOS:000273087800011,Proterozoic sedimentary exhalative (SEDEX) dep...,"[Article, Book]","[Article, Book Chapter]"
46,WOS:000370793800005,Turfgrass Benefits and Issues,"[Article, Book]","[Article, Book Chapter]"
47,WOS:000495572600004,Beyond Reproductive Isolation: Demographic Con...,"[Review, Book]","[Review, Book Chapter]"
48,WOS:000271405500024,Detrital zircon ages and Nd isotopic data from...,"[Article, Book]","[Article, Book Chapter]"
49,WOS:000443191400003,The OECD QSAR Toolbox Starts Its Second Decade,"[Article, Book]","[Article, Book Chapter]"

### Publishing Source, Publishing Date, Page Count

In [25]:
sourceTitle = pd.Series([])
publishYear = pd.Series([])
publishMonth = pd.Series([])
volume = pd.Series([])
issue = pd.Series([])
pages = pd.Series([])

for i in range(len(titleSource)):
    sourceTitle = pd.concat([sourceTitle, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['sourceTitle']]], ignore_index = True)
    publishYear = pd.concat([publishYear, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['publishYear']]], ignore_index = True)
    
    if 'publishMonth' not in pd.DataFrame.from_dict(dictTest['hits'][i]['source']).columns:
        publishMonth = pd.concat([publishMonth, pd.Series(['NA'])], ignore_index = True)
    else:
        publishMonth = pd.concat([publishMonth, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['publishMonth']]], ignore_index = True)

    if 'volume' not in pd.DataFrame.from_dict(dictTest['hits'][i]['source']).columns:
        volume = pd.concat([volume, pd.Series(['NA'])], ignore_index = True)
    else:
        volume = pd.concat([volume, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['volume']]], ignore_index = True)
    
    if 'issue' not in pd.DataFrame.from_dict(dictTest['hits'][i]['source']).columns:
        issue = pd.concat([issue, pd.Series(['NA'])], ignore_index = True)
    else:
        issue = pd.concat([issue, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['issue']]], ignore_index = True)
                           
    pages = pd.concat([pages, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['pages']]], ignore_index = True)

publisherInfo = pd.concat([sourceTitle, publishYear, publishMonth, volume, issue, pages], axis = 1)

publisherInfo = publisherInfo.drop(columns = [0, 1])

#publisherInfo

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

,sourceTitle,publishYear,volume,pages
0,ANNUAL REVIEW OF ECOLOGY EVOLUTION AND SYSTEMA...,2009.0,40,81-102
1,ANNUAL REVIEW OF PSYCHOLOGY,2009.0,60,631-652
2,"ANNUAL REVIEW OF MATERIALS RESEARCH, VOL 44",2014.0,44,241-267
3,"ANNUAL REVIEW OF MATERIALS RESEARCH, VOL 40",2010.0,40,271-292
4,ANNUAL REVIEW OF ECOLOGY EVOLUTION AND SYSTEMA...,2007.0,38,459-487
5,"ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTE...",2013.0,44,261-280
6,"ADVANCES IN FOOD AND NUTRITION RESEARCH, VOL 6...",2012.0,65,211-222
7,"ANNUAL REVIEW OF VIROLOGY, VOL 4",2017.0,4,201-219
8,FROM RODINIA TO PANGEA: THE LITHOTECTONIC RECO...,2010.0,206,1-19
9,INSECT MIDGUT AND INSECTICIDAL PROTEINS,2014.0,47,39-87
10,"ANNUAL REVIEW OF ENTOMOLOGY, VOL 66, 2021",2021.0,66,121-140
11,"ANNUAL REVIEW OF MATERIALS RESEARCH, VOL 49",2019.0,49,327-359
12,"ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTE...",2012.0,43,267-285
13,"ANNUAL REVIEW OF MARINE SCIENCE, VOL 7",2015.0,7,377-401
14,"ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTE...",2013.0,44,325-345
15,ANNUAL REVIEW OF NUTRITION,2006.0,26,75-103
16,"ADVANCES IN APPLIED MICROBIOLOGY, VOL 71",2010.0,71,149-184
17,DECISION MAKING THEORIES AND PRACTICES FROM AN...,2012.0,NaN,100-116
18,"ANNUAL REVIEW OF FOOD SCIENCE AND TECHNOLOGY, ...",2013.0,4,163-190
19,HANDBOOK OF RESEARCH IN INTERNATIONAL HUMAN RE...,2006.0,NaN,197-222
20,"ANNUAL REVIEW OF PLANT BIOLOGY, VOL 63",2012.0,63,239-260
21,PLANETARY TURN: RELATIONALITY AND GEOAESTHETIC...,2015.0,NaN,XI-267
22,"FOOD MICROBIOLOGY: FUNDAMENTALS AND FRONTIERS,...",2007.0,NaN,713-745
23,CHANGING BOUNDARIES OF PARENTAL AUTHORITY DURI...,2005.0,108,5-16
24,"ADVANCES IN EXPERIMENTAL SOCIAL PSYCHOLOGY, VO...",2010.0,43,205-255
25,"ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTE...",2019.0,50,303-333
26,CARBON IN EARTH,2013.0,75,7-46
27,"ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTE...",2020.0,51,561-586
28,"ADVANCES IN EXPERIMENTAL SOCIAL PSYCHOLOGY, VO...",2013.0,48,235-295
29,"INSECT PATHOLOGY, 2ND EDITION",2012.0,NaN,265-349
30,"COMPREHENSIVE NUCLEAR MATERIALS, VOL 1: BASIC ...",2012.0,NaN,357-391
31,"ADVANCES IN MOTIVATION SCIENCE, VOL 2",2015.0,2,185-241
32,COMPREHENSIVE GUIDE TO FACTORIAL TWO-LEVEL EXP...,2009.0,NaN,3-+
33,"ANNUAL REVIEW OF FOOD SCIENCE AND TECHNOLOGY, ...",2016.0,7,245-266
34,"POWER ELECTRONICS HANDBOOK: DEVICES, CIRCUITS,...",2007.0,NaN,451-482
35,"ADVANCES IN AGRONOMY, VOL 90",2006.0,90,267-297
36,STREAM RESTORATION IN DYNAMIC FLUVIAL SYSTEMS:...,2011.0,194,453-474
37,STRATIGRAPHIC ANALYSES USING GPR,2007.0,432,1-18
38,"ANNUAL REVIEW OF PHYTOPATHOLOGY, VOL 54",2016.0,54,443-468
39,"ADVANCES IN APPLIED MICROBIOLOGY, VOL 66",2009.0,66,53-75
40,"ANNUAL REVIEW OF PLANT BIOLOGY, VOL 69",2018.0,69,329-361
41,SPRINGER HANDBOOK OF ROBOTICS,2016.0,NaN,1335-1379
42,ORGANIC AMENDMENTS AND SOIL SUPPRESSIVENESS IN...,2015.0,46,277-305
43,POSITIVE AND NEGATIVE OUTCOMES OF SEXUAL BEHAV...,2014.0,144,3-19
44,YEAR IN ECOLOGY AND CONSERVATION BIOLOGY,2014.0,1322,61-76
45,"EVOLUTION OF EARLY EARTH'S ATMOSPHERE, HYDROSP...",2006.0,198,169-184
46,"TURFGRASS: BIOLOGY, USE, AND MANAGEMENT",2013.0,56,105-145
47,"ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTE...",2019.0,50,75-95
48,PROTEROZOIC TECTONIC EVOLUTION OF THE GRENVILL...,2004.0,197,459-475
49,COMPUTATIONAL TOXICOLOGY: METHODS AND PROTOCOLS,2018.0,1800,55-77

### Authors

In [157]:
authorNames = pd.Series([])
authorCount = pd.Series([])

for i in range(len(titleSource)):
    authorCount = pd.concat([authorCount, pd.Series([len(dictTest['hits'][i]['names']['authors'])])], ignore_index = True)

    authorString = ''
    for j in range(len(dictTest['hits'][i]['names']['authors'])):
        authorString = authorString + dictTest['hits'][i]['names']['authors'][j]['displayName'] + '; '

    authorNames = pd.concat([authorNames, pd.Series([authorString])], ignore_index = True)

authors = pd.concat([authorCount, authorNames], axis = 1)

authors.columns = ['authorCount', 'authorNames']

#authors

C:\Users\aharrima\AppData\Local\Temp\ipykernel_51840\2433469683.py:6: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  authorCount = pd.concat([authorCount, pd.Series([len(dictTest['hits'][i]['names']['authors'])])], ignore_index = True)

### Links

In [33]:
recordLink = pd.Series([])
citingArticlesLink = pd.Series([])
referenceLink = pd.Series([])
relatedLink = pd.Series([])

for i in range(len(titleSource)):
    recordLink = pd.concat([recordLink, pd.Series([dictTest['hits'][i]['links']['record']])], ignore_index = True)
    if 'citingArticles' in dictTest['hits'][i]['links']:
        citingArticlesLink = pd.concat([citingArticlesLink, pd.Series([dictTest['hits'][i]['links']['citingArticles']])], ignore_index = True)
    else:
        citingArticlesLink = pd.concat([citingArticlesLink, pd.Series(['None'])], ignore_index = True)
    if 'references' in dictTest['hits'][i]['links']:
        referenceLink = pd.concat([referenceLink, pd.Series([dictTest['hits'][i]['links']['references']])], ignore_index = True)
    else:
        referenceLink = pd.concat([referenceLink, pd.Series(['None'])], ignore_index = True)
    if 'related' in dictTest['hits'][i]['links']:
        relatedLink = pd.concat([relatedLink, pd.Series([dictTest['hits'][i]['links']['related']])], ignore_index = True)
    else:
        relatedLink = pd.concat([relatedLink, pd.Series(['None'])], ignore_index = True)

links = pd.concat([recordLink, citingArticlesLink, referenceLink, relatedLink], axis = 1)

links.columns = ['recordLink', 'citingArticlesLink', 'referenceLink', 'relatedLink']

#links

### Identifiers and Citations

In [37]:
citationCount = pd.Series([])
doi = pd.Series([])
ISSN = pd.Series([])
keywords = pd.Series([])

for i in range(len(titleSource)):
    citationCount = pd.concat([citationCount, pd.Series([dictTest['hits'][i]['citations'][0]['count']])], ignore_index = True)

    if 'doi' in dictTest['hits'][i]['identifiers']:
        doi = pd.concat([doi, pd.Series([dictTest['hits'][i]['identifiers']['doi']])], ignore_index = True)
    else:
        doi = pd.concat([doi, pd.Series(['NA'])], ignore_index = True)
    
    if 'eissn' in dictTest['hits'][i]['identifiers']:
        ISSN = pd.concat([ISSN, pd.Series([dictTest['hits'][i]['identifiers']['eissn']])], ignore_index = True)
    elif 'issn' in dictTest['hits'][i]['identifiers'] and 'eissn' not in dictTest['hits'][i]['identifiers']:
        ISSN = pd.concat([ISSN, pd.Series([dictTest['hits'][i]['identifiers']['issn']])], ignore_index = True)
    else:
        ISSN = pd.concat([ISSN, pd.Series(['NA'])], ignore_index = True)
        
    keywords = pd.concat([keywords, pd.Series([dictTest['hits'][i]['keywords']['authorKeywords']])], ignore_index = True)

idCite = pd.concat([citationCount, doi, ISSN, keywords], axis = 1)

idCite.columns = ['citationCount', 'doi', 'ISSN', 'keywords']

#idCite

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

C:\Users\aharrima\AppData\Local\Temp\ipykernel_63400\1588619565.py:8: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  citationCount = pd.concat([citationCount, pd.Series([dictTest['hits'][i]['citations'][0]['count']])], ignore_index = True)

### Combine all Parts Together

In [160]:
fullPublicationInfo = pd.concat([titleSource, publisherInfo, authors, links, idCite], axis = 1)

fullPublicationInfo

,uid,title,types,sourceTypes,sourceTitle,publishYear,publishMonth,volume,issue,pages,authorCount,authorNames,recordLink,citingArticlesLink,referenceLink,relatedLink,citationCount,doi,ISSN,keywords
0,WOS:001543361000014,The microbiome diversifies long-to short-chain...,[Article],[Article],CELL,2025.0,JUL 24,188,15,4154-4169,48,"Mannochio-Russo, Helena; Charron-Lamoureux, Vi...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,11,10.1016/j.cell.2025.05.015,1097-4172,[]
1,WOS:001373010000001,Scientific exploration with expert knowledge (...,[Article],[Article],DIGITAL DISCOVERY,2025.0,JAN 15,4,1,252-263,5,"Pratiush, Utkarsh; Funakubo, Hiroshi; Vasudeva...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,8,10.1039/d4dd00277f,2635-098X,[]
2,WOS:001369650000001,Advancements of PAPI for the exascale generation,[Article],[Article],INTERNATIONAL JOURNAL OF HIGH PERFORMANCE COMP...,2025.0,MAR,39,2,251-268,6,"Jagode, Heike; Danalis, Anthony; Congiu, Giuse...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,5,10.1177/10943420241303884,1741-2846,"[Performance monitoring, power monitoring, ene..."
3,WOS:001468571900001,Single-Ion Conducting Polymer Electrolyte Enab...,[Article],[Article],MACROMOLECULES,2025.0,APR 16,58,9,4708-4714,6,"Lehmann, Michelle L.; Ock, Jiyoung; Gainaru, C...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,5,10.1021/acs.macromol.5c00422,1520-5835,[]
4,WOS:001476711300001,AI Chatbots and Subject Cataloging A Performan...,[Article],[Article],LIBRARY RESOURCES & TECHNICAL SERVICES,2025.0,APR,69,2,14,2,"Dobreski, Brian; Hastings, Christopher;",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,2,10.5860/lrts.69n2.8440,2159-9610,[]
5,WOS:001451276700005,Student Engagement in Academic Libraries: A Co...,[Article],[Article],COLLEGE & RESEARCH LIBRARIES,2025.0,MAR,86,2,275-293,4,"Zhu, Xiaohua Awa; Whitaker, Erin E.; Cho, Moon...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,3,10.5860/crl.86.2.275,2150-6701,[]
6,WOS:001324301600001,Evolution of the SLATE linear algebra library,[Article],[Article],INTERNATIONAL JOURNAL OF HIGH PERFORMANCE COMP...,2025.0,JAN,39,1,3-17,11,"Gates, Mark; Abdelfattah, Ahmad; Akbudak, Kadi...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,3,10.1177/10943420241286531,1741-2846,"[High-performance computing, graphics processi..."
7,WOS:001453134100001,Battle Royale Optimization for Optimal Band Se...,[Article],[Article],JOURNAL OF IMAGING,2025.0,MAR 17,11,3,21,7,"Ramasamy, Jagadeeswaran; Raju, Anand; Ranganat...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,2,10.3390/jimaging11030083,2313-433X,"[spectral techniques, soil properties, machine..."
8,WOS:001428592200001,SANE: strategic autonomous non-smooth explorat...,[Article],[Article],DIGITAL DISCOVERY,2025.0,MAR 12,4,3,853-867,6,"Biswas, Arpan; Vasudevan, Rama; Pant, Rohit; T...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,2,10.1039/d4dd00299g,2635-098X,[]
9,WOS:001244616400003,Towards a platform-portable linear algebra bac...,[Article],[Article],MECCANICA,2025.0,JUN,60,6,1659-1672,4,"Olenik, Gregor; Koch, Marcel; Boutanios, Ziad;...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,2,10.1007/s11012-024-01806-1,1572-9648,"[Computational fluid dynamics, OpenFOAM, Ginkg..."
10,WOS:001560851000001,Materials discovery in combinatorial and high-...,[Review],[Review],APPLIED PHYSICS REVIEWS,2025.0,SEP,12,3,30,16,"Slautin, Boris N.; Liu, Yongtao; Barakati, Kam...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,2,10.1063/5.0259851,1931-9401,[]
11,WOS:001538779200041,The information needs and behaviours of creati...,[Article],[Article],INFORMATION RESEARCH-AN INTERNATIONAL ELECTRON...,2025.0,JUN,30,COLIS,551-566,1,"Fleming-May, Rachel A.;",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.47989/ir30CoLIS52315,1368-1613,[]
12,WOS:001527368200001,Development of CRISPRi Orthogonal Repression S...,[Article],[Article],ACS SYNTHETIC BIOLOGY,2025.0,AUG 15,14,8,3219-3231,8,"Majdi, Mohammad; Wahl, Nancy J.; Li, Li; King,...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1021/acssynbio.5c00356,2161-5063,"[Figwort Mosaic Virus (FMV) 34S promoter, CRIS..."
13,WOS:001492947900001,Adiabatic quantum support vector machines,[Article],[Article],QUANTUM MACHINE INTELLIGENCE,2025.0,MAY 22,7,1,14,10,"Date, Prasanna; Woun, Dong Jun; Hamilton, Kath...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1007/s42484-025-00280-6,2524-4914,"[Quantum machine learning, Quantum AI, Support..."
14,WOS:001478122000001,Building workflows for an interactive human-in...,[Article],[Article],DIGITAL DISCOVERY,2025.0,MAY 14,4,5,1323-1338,6,"Pratiush, Utkarsh; Roccapriore, Kevin M.; Liu,...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1039/d5dd00033e,2635-098X,[]
15,WOS:001470225800001,Optimizing Cost-Effective gene expression phen...,[Article],[Article],BMC GENOMICS,2025.0,APR 16,26,1,13,6,"Mohamed, Ruwaa I.; Ault-Seay, Taylor B.; Moisa...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1186/s12864-025-11571-4,1471-2164,"[Molecular phenotyping, Gene expression, High-..."
16,WOS:001427703200001,How do LGBTQ plus library catalog users talk a...,[Article],[Article],JOURNAL OF DOCUMENTATION,2025.0,APR 28,81,3,581-597,3,"Moulaison-Sandy, Heather; Dobreski, Brian; Sno...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1108/JD-10-2024-0257,1758-7379,"[LGBTQ plus community, Library users, Code-swi..."
17,WOS:001404519000001,High-Throughput Oxford Nanopore Sequencing Unv...,[Article],[Article],VIRUSES-BASEL,2025.0,JAN,17,1,17,4,"Ranabhat, Nar B.; Fellers, John P.; Bruce, Myr...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.3390/v17010126,1999-4915,"[wheat virus, virome, RNA viruses, phylogeny, ..."
18,WOS:001400540400001,Immersive Videography of Ancient DNA Extractio...,[Article],[Article],AMERICAN JOURNAL OF BIOLOGICAL ANTHROPOLOGY,2025.0,JAN 21,186,1,11,6,"Fleskes, Raquel E.; Gilmore, Joanna K.; Oubre,...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1002/ajpa.25055,2692-7691,"[education, GoPro, outreach, paleogenomics, vi..."
19,WOS:001571402800001,Neuroimaging Findings in Children and Young Ad...,[Article],[Article],NEUROLOGY,2025.0,OCT 7,105,7,13,25,"McGuire, Jennifer L.; Pinto, Soniya; Erdogan, ...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1212/WNL.0000000000214086,1526-632X,[]
20,WOS:001546036500001,Toward a monocot SynBio toolkit: assessing reg...,[Article],[Article],PLANT CELL REPORTS,2025.0,AUG 8,44,9,15,11,"May, David B.; Pfotenhauer, Alexander C.; Conc...",https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,1,10.1007/s00299-025-03583-x,1432-203X,"[Synthetic biology, Monocots, Transgene expres..."
21,WOS:001501493100001,Efficient solution of batched band linear syst...,[Article],[Article],INTERNATIONAL JOURNAL OF HIGH PERFORMANCE COMP...,2025.0,SEP,39,5,615-630,3,"Nayak, Pratik; Aggarwal, Isha; Anzt, Hartwig;",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1177/10943420251347460,1741-2846,"[batched algorithms, band linear systems, GPU ..."
22,WOS:001469542600047,'A Mulligan's stew': educational preparation f...,[Article],[Article],INFORMATION RESEARCH-AN INTERNATIONAL ELECTRON...,2025.0,MAR,30,NaN,1234-1243,3,"Fleming-May, Rachel; Bishop, Wade; Villarreal,...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.47989/ir30iConf46912,1368-1613,[]
23,WOS:001455819200001,Breaking boundaries: Investigating gender bias...,[Article],[Article],COLLEGE & UNDERGRADUATE LIBRARIES,2025.0,APR 3,32,1-2,26-37,3,"Gavel, Sidney; Wood, Mikayla Grace; Williamson...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1080/10691316.2025.2482522,1545-2530,"[Academic libraries, artificial intelligence, ..."
24,WOS:001435715200001,Learning from digital disorientations: Navigat...,[Article],[Article],LIBRARY & INFORMATION SCIENCE RESEARCH,2025.0,JAN,47,1,7,5,"Wagner, Travis L.; Montague, Kaitlin; Kitzie, ...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1016/j.lisr.2025.101340,1873-1848,"[COVID-19, Virtual research, Comparative case ..."
25,WOS:001427063200001,Usability: comparison of DataONE on four unive...,[Article],[Article],PERFORMANCE MEASUREMENT AND METRICS,2025.0,MAR 6,26,1,71-84,2,"Cannon, Leah; Volentine, Rachel;",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1108/PMM-09-2021-0050,1758-6925,"[LibGuides, Usability, Eye-tracking, DataONE, ..."
26,WOS:001409931800001,How are library cataloging metadata used diffe...,[Article],[Article],JOURNAL OF DOCUMENTATION,2025.0,FEB 25,81,2,385-402,3,"Li, Kai; Dobreski, Brian; Busch, Molly;",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1108/JD-08-2024-0199,1758-7379,"[Library cataloging, Metadata, Data science, M..."
27,WOS:001408653800001,Invariant discovery of features across multipl...,[Article],[Article],JOURNAL OF APPLIED PHYSICS,2025.0,JAN 21,137,3,14,9,"Raghavan, Aditya; Pratiush, Utkarsh; Valleti, ...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1063/5.0233070,1089-7550,[]
28,WOS:001339832100001,Serials Spoken Here,[Article],[Article],SERIALS REVIEW,2025.0,APR 3,51,1-2,65-81,12,"Urquieta Cortes, Christy; Sutton, Sarah W.; Ha...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1080/00987913.2024.2411658,1879-095X,"[Database cancelations, e-resource librariansh..."
29,WOS:001664529300008,Generating Spiking Neural Network Code Librari...,[Meeting],[Proceedings Paper],2025 INTERNATIONAL CONFERENCE ON NEUROMORPHIC ...,2025.0,NaN,NaN,NaN,57-64,6,"Gullett, Bryson; Mowry, Jackson; Plank, James ...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1109/ICONS69015.2025.00019,NA,"[spiking neural networks, neuromorphic computi..."
30,WOS:001665533400073,pyGinkgo: A Sparse Linear Algebra Operator Fra...,[Meeting],[Proceedings Paper],54TH INTERNATIONAL CONFERENCE ON PARALLEL PROC...,2025.0,NaN,NaN,NaN,753-763,8,"Tuteja, Keshvi; Olenik, Gregor; Mishchuk, Roma...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1145/3754598.3754648,NA,"[Sparse Linear Algebra, Performance Optimizati..."
31,WOS:001661298800054,On the integration of lightweight tasks with M...,[Meeting],[Proceedings Paper],PROCEEDINGS OF 2025 WORKSHOPS OF THE INTERNATI...,2025.0,NaN,NaN,NaN,489-499,7,"Biddiscombe, John; Simberg, Mikael; Reverdell,...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1145/3731599.3767394,NA,"[C plus, MPI, Senders, Asynchronous, Task, Run..."
32,WOS:001611311200177,The Fluid Dynamics Uncertainty Quantification ...,[Meeting],[Proceedings Paper],AIAA AVIATION FORUM AND ASCEND 2025,2025.0,NaN,NaN,NaN,32,3,"Lay, Aidan S.; Weinmeister, Justin; Sanjaya, D...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.2514/6.2025-3872,NA,[]
33,WOS:001655763100001,Pyrometheus: Symbolic abstractions for XPU and...,[Article],[Article],COMPUTER PHYSICS COMMUNICATIONS,2026.0,MAR,320,NaN,21,5,"Cisneros-Garibay, Esteban; Le Berre, Henry; Ad...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1016/j.cpc.2025.109987,1879-2944,"[Combustion kinetics & thermodynamics, GPUs & ..."
34,WOS:001642550600001,LaBr3: Ce self-activation analysis for measuri...,[Article],[Article],NUCLEAR INSTRUMENTS & METHODS IN PHYSICS RESEA...,2026.0,APR,1084,NaN,9,8,"Wilson, Caryanne R.; Searfus, Oskar; Fondement...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1016/j.nima.2025.171223,1872-9576,"[D-T neutron generator, Neutron yield, Neutron..."
35,WOS:001591519400028,On Optimizing Checkpoint Restoration for HPC A...,[Meeting],[Proceedings Paper],INTERNATIONAL SYMPOSIUM ON HIGH-PERFORMANCE PA...,2025.0,NaN,NaN,NaN,2,7,"Malkmus, Zackary; Tan, Nigel; Lumsden, Ian; As...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1145/3731545.3735116,NA,[]
36,WOS:001618773800001,Modeling and Evaluating Superconducting Ferroe...,[Article],[Article],IEEE TRANSACTIONS ON QUANTUM ENGINEERING,2025.0,NaN,6,NaN,11,6,"Parihar, Shivendra Singh; Klemme, Florian; Ala...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1109/TQE.2025.3619944,2689-1808,"[SQUIDs, Circuits, Integrated circuit modeling..."
37,WOS:001611051700001,A cross-platform execution engine for the quan...,[Article],[Article],JOURNAL OF SUPERCOMPUTING,2025.0,NOV 5,81,16,21,9,"Wong, Elaine; Leyton-Ortega, Vicente; Claudino...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1007/s11227-025-07969-2,1573-0484,"[Quantum computing, Intermediate representatio..."
38,WOS:001599558200001,"Spectroscopy of the Hamburg Meteorite, Michiga...",[Article],[Article],PLANETARY SCIENCE JOURNAL,2025.0,OCT 1,6,10,13,13,"Dyar, M. Darby; Breitenfeld, Laura B.; Lane, M...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.3847/PSJ/ae0a4f,2632-3338,[]
39,WOS:001589093200002,Extending Embedded Monte Carlo as a novel meth...,[Article],[Article],EPJ NUCLEAR SCIENCES & TECHNOLOGIES,2025.0,OCT 8,11,NaN,12,5,"Biot, Gregoire; Ducru, Pablo; Sobes, Vladimir;...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1051/epjn/2025052,2491-9292,[]
40,WOS:001578852100001,Mapping causal patterns in crystalline solid,[Article],[Article],APL MACHINE LEARNING,2025.0,SEP,3,3,13,8,"Barakati, Kamyar; Nelson, Chris; Morozovska, A...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1063/5.0284465,2770-9019,[]
41,WOS:001576905100007,CONFLUX: A standardized framework to calculate...,[Article],[Article],COMPUTER PHYSICS COMMUNICATIONS,2025.0,DEC,317,NaN,15,9,"Zhang, Xianyi; Irani, Anosh; Mendenhall, Micha...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1016/j.cpc.2025.109831,1879-2944,"[Neutrino physics, Nuclear data, Fission]"
42,WOS:001549114000006,Comparison of Librarian and Patron Ratings of ...,[Article],[Article],COLLEGE & RESEARCH LIBRARIES,2025.0,JUL,86,4,567-585,2,"Owens, Erin Elizabeth; Brooks, Kat;",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.5860/crl.86.4.567,2150-6701,[]
43,WOS:001568096400001,Design of Quasi-Integral Experiments at the Fl...,"[Article, Early Access]","[Article, Early Access]",NUCLEAR SCIENCE AND ENGINEERING,2025.0,SEP 12,NaN,NaN,27,4,"Lewis, A. M.; Sobes, V.; Williams, A.; Bogetic...",https://www.webofscience.com/api/gateway?GWVer...,None,https://www.webofscience.com/api/gateway?GWVer...,https://www.webofscience.com/api/gateway?GWVer...,0,10.1080/00295639.2025.2522484,1943-748X,"[Integral experiment, quasi-integral experimen..."

### Export the Page to Excel

In [162]:
fullPublicationInfo.to_excel('API Test Run Web of Science.xlsx', index = False)

# Web of Science Bulk Gathering 

This part of the code combines every piece seen above into one cell, so many pages can be gathered at one time. If you are unsure how many items fit your query, go to the "Check the Query Size" cell above. 


## NOTE: Web of Science caps each person's daily publication gathering at 5,000 items. If you are gathering more than 5000 items, you will need to spread out the gathering over multiple days or get it from the WoS website.

In [13]:
allQuery = pd.DataFrame()

configuration = clarivate.wos_starter.client.Configuration(
    host = "https://api.clarivate.com/apis/wos-starter/v1"
)

# Load the API Key

os.environ["API_KEY"] = getpass.getpass('Enter your Web of Science API Key:')

# Configure API key authorization: ClarivateApiKeyAuth
configuration.api_key['ClarivateApiKeyAuth'] = os.environ["API_KEY"]


# Set the number of pages needed for your query here

numPages = 24

for page in range(1, numPages + 1):
    print(r'Page '+str(page)+' Gathering...')
    with clarivate.wos_starter.client.ApiClient(configuration) as api_client:
        # Create an instance of the API class
        api_instance = clarivate.wos_starter.client.DocumentsApi(api_client)
        query = '(OG=(University of Tennessee Knoxville)) AND PY=(2026)'
        database = 'WOS' # Web of Science Database abbreviation * WOS - Web of Science Core collection * BIOABS - Biological Abstracts * BCI - BIOSIS Citation Index * BIOSIS - BIOSIS Previews * CCC - Current Contents Connect * DIIDW - Derwent Innovations Index * DRCI - Data Citation Index * MEDLINE - MEDLINE The U.S. National Library of Medicine® (NLM®) premier life sciences database. * ZOOREC - Zoological Records * PPRN - Preprint Citation Index * WOK - All databases  (optional) (default to 'WOS')
        recordLimit = 50 # set the limit of records on the page (1-50) (optional) (default to 10)
        resultPage = page # set the result page (optional) (default to 1)
        sort_field = 'TC+D' # Order by field(s). Field name and order by clause separated by '+', use A for ASC and D for DESC, ex: PY+D. Multiple values are separated by comma. Supported fields:  * **LD** - Load Date * **PY** - Publication Year * **RS** - Relevance * **TC** - Times Cited  (optional)
        modified_time_span = None # Defines a date range in which the results were most recently modified. Beginning and end dates must be specified in the yyyy-mm-dd format separated by '+' or ' ', e.g. 2023-01-01+2023-12-31. This parameter is not compatible with the all databases search, i.e. db=WOK is not compatible with this parameter. (optional)
        tc_modified_time_span = None # Defines a date range in which times cited counts were modified. Beginning and end dates must be specified in the yyyy-mm-dd format separated by '+' or ' ', e.g. 2023-01-01+2023-12-31. This parameter is not compatible with the all databases search, i.e. db=WOK is not compatible with this parameter. (optional)
        detail = None # it will returns the full data by default, if detail=short it returns the limited data (optional)
    
        try:
            # Query Web of Science documents 
            api_response = api_instance.documents_get(query, 
                                                      db=database, 
                                                      limit=recordLimit,
                                                      page=resultPage, 
                                                      sort_field=sort_field, 
                                                      modified_time_span=modified_time_span, 
                                                      tc_modified_time_span=tc_modified_time_span, 
                                                      detail=detail)
            #print("The response of DocumentsApi->documents_get:\n")
            #pprint(api_response)
        except ApiException as e:
            print("Exception when calling DocumentsApi->documents_get: %s\n" % e)
            break

        # Convert to Dictionary
        dictTest = api_response.to_dict()

        
        # uID, Title, Source Type
        titleSource = pd.DataFrame.from_dict(dictTest['hits'])[['uid', 'title', 'types', 'sourceTypes']]

        
        # Publishing Source, Publishing Date, Page Count
        sourceTitle = pd.Series([])
        publishYear = pd.Series([])
        publishMonth = pd.Series([])
        volume = pd.Series([])
        issue = pd.Series([])
        pages = pd.Series([])
        
        for i in range(len(titleSource)):
            sourceTitle = pd.concat([sourceTitle, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['sourceTitle']]], ignore_index = True)
            publishYear = pd.concat([publishYear, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['publishYear']]], ignore_index = True)
            
            if 'publishMonth' not in pd.DataFrame.from_dict(dictTest['hits'][i]['source']).columns:
                publishMonth = pd.concat([publishMonth, pd.Series(['NA'])], ignore_index = True)
            else:
                publishMonth = pd.concat([publishMonth, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['publishMonth']]], ignore_index = True)
        
            if 'volume' not in pd.DataFrame.from_dict(dictTest['hits'][i]['source']).columns:
                volume = pd.concat([volume, pd.Series(['NA'])], ignore_index = True)
            else:
                volume = pd.concat([volume, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['volume']]], ignore_index = True)
            
            if 'issue' in pd.DataFrame.from_dict(dictTest['hits'][i]['source']).columns:
                issue = pd.concat([issue, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['issue']]], ignore_index = True)
            else:
                issue = pd.concat([issue, pd.Series(['NA'])], ignore_index = True)
                                   
            pages = pd.concat([pages, pd.DataFrame.from_dict(dictTest['hits'][i]['source']).head(1)[['pages']]], ignore_index = True)
        
        publisherInfo = pd.concat([sourceTitle, publishYear, publishMonth, volume, issue, pages], axis = 1)

        if 0 in publisherInfo.columns and 1 in publisherInfo.columns:
            publisherInfo = publisherInfo = publisherInfo.drop(columns = [0, 1])
        elif 0 in publisherInfo.columns:
            publisherInfo = publisherInfo = publisherInfo.drop(0, axis = 1)
        elif 1 in publisherInfo.columns:
            publisherInfo = publisherInfo = publisherInfo.drop(1, axis = 1)
        else:
            publisherInfo = publisherInfo


        # Authors
        authorNames = pd.Series([])
        authorCount = pd.Series([])
        
        
        for i in range(len(titleSource)):
            authorCount = pd.concat([authorCount, pd.Series([len(dictTest['hits'][i]['names']['authors'])])], ignore_index = True)
        
            authorString = ''
            for j in range(len(dictTest['hits'][i]['names']['authors'])):
                authorString = authorString + dictTest['hits'][i]['names']['authors'][j]['displayName'] + '; '
        
            authorNames = pd.concat([authorNames, pd.Series([authorString])], ignore_index = True)
        
        authors = pd.concat([authorCount, authorNames], axis = 1)
        
        authors.columns = ['authorCount', 'authorNames']


        # Links
        recordLink = pd.Series([])
        citingArticlesLink = pd.Series([])
        referenceLink = pd.Series([])
        relatedLink = pd.Series([])
        
        for i in range(len(titleSource)):
            recordLink = pd.concat([recordLink, pd.Series([dictTest['hits'][i]['links']['record']])], ignore_index = True)
            if 'citingArticles' in dictTest['hits'][i]['links']:
                citingArticlesLink = pd.concat([citingArticlesLink, pd.Series([dictTest['hits'][i]['links']['citingArticles']])], ignore_index = True)
            else:
                citingArticlesLink = pd.concat([citingArticlesLink, pd.Series(['None'])], ignore_index = True)
            if 'references' in dictTest['hits'][i]['links']:
                referenceLink = pd.concat([referenceLink, pd.Series([dictTest['hits'][i]['links']['references']])], ignore_index = True)
            else:
                referenceLink = pd.concat([referenceLink, pd.Series(['None'])], ignore_index = True)
            if 'related' in dictTest['hits'][i]['links']:
                relatedLink = pd.concat([relatedLink, pd.Series([dictTest['hits'][i]['links']['related']])], ignore_index = True)
            else:
                relatedLink = pd.concat([relatedLink, pd.Series(['None'])], ignore_index = True)
        
        links = pd.concat([recordLink, citingArticlesLink, referenceLink, relatedLink], axis = 1)
        
        links.columns = ['recordLink', 'citingArticlesLink', 'referenceLink', 'relatedLink']


        # Identifiers and Citations
        citationCount = pd.Series([])
        doi = pd.Series([])
        ISSN = pd.Series([])
        keywords = pd.Series([])
        
        for i in range(len(titleSource)):
            citationCount = pd.concat([citationCount, pd.Series([dictTest['hits'][i]['citations'][0]['count']])], ignore_index = True)
            
            if 'doi' in dictTest['hits'][i]['identifiers']:
                doi = pd.concat([doi, pd.Series([dictTest['hits'][i]['identifiers']['doi']])], ignore_index = True)
            else:
                doi = pd.concat([doi, pd.Series(['NA'])], ignore_index = True)
                    
            if 'eissn' in dictTest['hits'][i]['identifiers']:
                ISSN = pd.concat([ISSN, pd.Series([dictTest['hits'][i]['identifiers']['eissn']])], ignore_index = True)
            elif 'issn' in dictTest['hits'][i]['identifiers'] and 'eissn' not in dictTest['hits'][i]['identifiers']:
                ISSN = pd.concat([ISSN, pd.Series([dictTest['hits'][i]['identifiers']['issn']])], ignore_index = True)
            else:
                ISSN = pd.concat([ISSN, pd.Series(['NA'])], ignore_index = True)
                
            keywords = pd.concat([keywords, pd.Series([dictTest['hits'][i]['keywords']['authorKeywords']])], ignore_index = True)
        
        idCite = pd.concat([citationCount, doi, ISSN, keywords], axis = 1)
        
        idCite.columns = ['citationCount', 'doi', 'ISSN', 'keywords']


        # All Columns
        fullPublicationInfo = pd.concat([titleSource, publisherInfo, authors, links, idCite], axis = 1)

    allQuery = pd.concat([allQuery, fullPublicationInfo], ignore_index = True)

allQuery.shape

Page 1 Gathering...
Page 2 Gathering...
Page 3 Gathering...
Page 4 Gathering...
Page 5 Gathering...
Page 6 Gathering...
Page 7 Gathering...
Page 8 Gathering...
Page 9 Gathering...
Page 10 Gathering...
Page 11 Gathering...
Page 12 Gathering...
Page 13 Gathering...
Page 14 Gathering...
Page 15 Gathering...
Page 16 Gathering...
Page 17 Gathering...
Page 18 Gathering...
Page 19 Gathering...
Page 20 Gathering...
Page 21 Gathering...
Page 22 Gathering...
Page 23 Gathering...
Page 24 Gathering...

(1152, 20)

In [14]:
allQuery.to_excel('UT Publishing Web of Science 2026.xlsx', index = False)

# Next Steps:

### Looking to gather OpenAlex publishing data?

Check out the "Gathering OpenAlex Articles Using API" R code.

### Looking to combine the data you just gathered together?

The "UT Summary of Publications", "Peer Institution Summary of Publications", and/or "UT System Publication Joining" files show how to join publishing data in various ways. These are designed with the full record in mind, so they may need some edits for the API data.

### Does the API not provide the detail you are looking for?

You may have to go to the websites and directly download publishing data from there. Both websites allow for the same searching method used here, so you can keep the process consistent.

### Looking to gather Dimensions or Academic Analytics publishing data?

Neither Dimensions nor Academic Analytics have an API of any description, so you'll need to download that data from the websites directly.

## Publisher Name from Scopus Test Code 

This code does work, but is very slow. It is not recommended for very large collections of articles from Scopus.

In [ ]:
publicationNameFrame = pd.DataFrame()

for i in range(100):#len(scopusPubsUTK['publicationName'])):
    if i % 10 == 0:
        print(i)
    if i != 0:
        titlesFound = set(publicationNameFrame['title'].unique())
        
    serialQuery = SerialTitleSearch(query = {"title": scopusPubsUTK['publicationName'].iloc[i]}, view = 'STANDARD')
    if serialQuery.get_results_size() == 0:
        print('No items found')
        continue
    else:
        serialTest = pd.DataFrame(serialQuery.results)
        if publicationNameFrame.shape[0] == 0:
            serialTest = serialTest[['title', 'publisher', 'subject_area_names']]
            publicationNameFrame = serialTest
            continue
        elif serialTest['title'].iloc[0] in set(titlesFound):
            print('Title Already in List')
            continue
        else:
            serialTest = serialTest[['title', 'publisher', 'subject_area_names']]
            publicationNameFrame = pd.concat([publicationNameFrame, serialTest], ignore_index=True)